image: docker:latest

variables:
  GOOGLE_TAG: eu.gcr.io/papers-kubernetes/$NAMESPACE:$CI_COMMIT_SHA

stages:
  - build
  - test

build_ionic:
  stage: build
  script:
    - docker build -t $GOOGLE_TAG .
  tags:
    - docker

unit:
  stage: test
  script:
    - docker run --name unit-$CI_COMMIT_SHA $GOOGLE_TAG npm run test
    - docker cp unit-$CI_COMMIT_SHA:/app/src/coverage/report-lcov/lcov.info lcov.info
  after_script:
    - docker rm unit-$CI_COMMIT_SHA
  tags:
    - docker
  artifacts:
    paths:
      - lcov.info
